### PR TITLE
:up: Update travis rubies

### PR DESCRIPTION
**Pull request by sanemat**
- Add ruby 2.3
- Add ruby 2.4
- Avoid errors on edge case

Next step: Update rspec to v3

### CODE REVIEW

**Comment by christhekeele** [comment]
Would the `rake` issue be better avoided by bumping the development dependency in the `.gemspec` instead to `11.3`? Would we need to pin it to *under* `12.0`? I'm not really clear where  `last_comment` is coming into play.

**Comment by sanemat** [comment]
@christhekeele 
I think pinning rake `v11.3` is temporary solution, so I don't add this to original `.gemspec`.
This is rspec `v2` issue, we should update rspec to `v3`, soon :)

**Comment by christhekeele** [comment]
Just to clarify, if we bumped rspec, then these rake changes wouldn't be necessary? I think I'd rather have the full fix later then a larger matrix of ruby versions sooner.

**Comment by sanemat** [comment]
Answer is yes, rspec 2.14 uses `::Rake.application.last_comment`.
https://travis-ci.org/nathanl/authority/jobs/190024617#L212
https://github.com/rspec/rspec-core/blob/2-14-maintenance/lib/rspec/core/rake_task.rb#L118

I agree with shrinking ruby/rails version!
I also think we want to have green test first.

**Pull request merged**
