### PR TITLE
Fix Bundler on Travis CI

### PR DESCRIPTION
**Pull request by dteoh**
Let's see how this goes...

### CODE REVIEW

**Comment by nathanl** [comment]
👍 👍 !! :smile: Thanks so much! It's soooo nice to have help with chores like that. Thanks for figuring out the problem!

**Comment by nathanl** [comment]
Noted in the changelog for next version - https://github.com/nathanl/authority/commit/e2d2b7c9e3c6ca60b6cfe3e0fed5dc9487e88a66

Not doing a release right now since there are no actual code changes, but I really appreciate your work.

**Comment by christhekeele** [comment]
This is now released 🎉

**Comment by nathanl** [comment]
👍

**Pull request merged**
